# CHOIX DE L'AFFICHAGE !!! ( ncurses, sdl, sfml )
LIB_AFF = ncurses
# Compilateur
CXX = g++
# Flags de Compilation
CFLAGS := -W -Wall -Wextra -Wdeprecated -Wuninitialized -Wunused-variable -Wvariadic-macros -Winline -Wredundant-decls -Wunused-macros
#CFLAGS += -Wpadded -Werror
# A NE PAS UTILISER AVEC SDL
#CFLAGS += -fshort-enums
#Flags pour le linker
# Permet d'inclure en dure les dll : libgcc_s_dw2-1.dll, libstdc++-6.dll
#LDFLAGS := -static-libstdc++ -static-libgcc
LDFLAGS :=
# Mode Debug (décommenter cette ligne pour activer le mode debug forcé) (identique a la commande: make debug)
#DEBUG = 1
# Lancer automatiquement gdb après chaque compilation en mode debug ( make exec ! )
DEBUG_AUTO_EXEC_GDB = oui
# Tracage mémoire (no leaks) (décommenter cette ligne pour activer le mode debug forcé) (identique a la commande: make memcheck)
DEBUG_MEMORY = 1

# Fichiers contenant les dépendances
DEP = .depend
# Fichiers .cpp
SRC := main.cpp map.cpp perso.cpp partie.cpp clavier.cpp options.cpp bonus.cpp outils.cpp
SRC += ClientServer/Server/class_server.cpp ClientServer/Client/class_client.cpp ClientServer/class_BaseClientServer.cpp
# Fichier de sortie final
EXEC_NAME = bomberman.exe

# Zones de sorties
BIN_DIR = bin
OBJ_DIR = obj
DOXYGEN_DIR = doc


################################################################################
# v NE PAS TOUCHER A CE BLOCK v
# Determine l'OS sur lequel on tourne
ifeq ($(SHELL), sh.exe)
	OS = win
	# Commandes Spé aux OS
	CMD_DEL = del /F
	CMD_CLEAR = cls
	CMD_LINEFEED = @echo. && @echo . > NUL
	CMD_SED = "%CD%\.tools\sed.exe"
	CMD_CAT = type
	ECHO=@echo $(1)$(if $(2),$(ECHO_,)$(2))$(if $(3),$(ECHO_,)$(3))$(if $(4),$(ECHO_,)$(4))$(if $(5),$(ECHO_,)$(5))
	NULL = NUL
	LDFLAGS += -lws2_32
else
	OS = linux
	# Commandes Spé aux OS
	CMD_DEL = /bin/rm -f
	CMD_CLEAR = clear
	CMD_LINEFEED = @echo ""
	CMD_SED = /bin/sed
	CMD_CAT = /bin/cat
	ECHO=@echo "$(1)$(if $(2),$(ECHO_,)$(2))$(if $(3),$(ECHO_,)$(3))$(if $(4),$(ECHO_,)$(4))$(if $(5),$(ECHO_,)$(5))"
	NULL = /dev/null
endif
# La règle no_clear permet de supprimer la commande d'effacement d'écran
ifneq ($(findstring no_clear,$(MAKECMDGOALS)),)
	CMD_CLEAR =
endif
# Les ECHO_XXX sont là pour permettre le passage de certains caractères (dans des fonctions) qui ne passent pas sinon
ECHO_,=,
ECHO_)=)
ECHO_(=(

# Determine si un la lib a été spécifié
ifeq ($(findstring sdl,$(MAKECMDGOALS)) ,ncurses)
	LIB_AFF = ncurses
else
	ifeq ($(findstring sdl,$(MAKECMDGOALS)) ,sdl)
		LIB_AFF = SDL
	else
		ifeq ($(findstring sdl,$(MAKECMDGOALS)) ,sfml)
			LIB_AFF = SFML
		endif
	endif
endif

# Ajustement des directives de précompilation
CFLAGS += -D__LIB_${LIB_AFF}__

# Mode débug mémoire ?
USE_DEBUG_MEMORY = $(or $(findstring memcheck,$(MAKECMDGOALS)),$(findstring memchk,$(MAKECMDGOALS)),$(DEBUG_MEMORY))
ifneq ($(USE_DEBUG_MEMORY),)
	CFLAGS += -D__DEBUG_MEMORY__
	SRC += debug_memory.cpp
endif

# Met en mode debug ou non
USE_DEBUG = $(or $(findstring debug,$(MAKECMDGOALS)),$(DEBUG))
ifneq ($(USE_DEBUG),)
	CFLAGS += -ggdb3
endif

# Lib a utiliser ( /!\ Peut changer en fonction de l'OS OU du système d'affichage /!\ )
ifeq ($(LIB_AFF), ncurses)
#	NCURSES
	ifeq ($(OS),win)
		LDFLAGS += -lpdcurses
	else
		LDFLAGS += -lncurses
	endif
	SRC += moteur_ncurses.cpp
else
	ifeq ($(LIB_AFF), SDL)
# 		SDL
		ifeq ($(OS), win)
			LDFLAGS += -lmingw32 -lSDLmain
		endif
#		NOTE: -mwindows permet de virer la console
		LDFLAGS += -lSDL -lSDL_ttf -lSDL_image $(if $(USE_DEBUG) ,,-mwindows)
		SRC += moteur_sdl.cpp
	else
#		SFML
		LDFLAGS += -lsfml-system -lsfml-window
		SRC += moteur_sfml.cpp
	endif
endif

# Fichiers Objets ( *.o ) dans un dossier obj/
OBJ_FILES = $(addprefix $(OBJ_DIR)/,$(notdir $(SRC:.cpp=.o)))
VPATH = $(dir $(SRC))

# ^ NE PAS TOUCHER A CE BLOCK ^
################################################################################

# Simple Make
all: $(BIN_DIR)/$(EXEC_NAME)
$(BIN_DIR)/$(EXEC_NAME): $(BIN_DIR) $(OBJ_DIR) $(OBJ_DIR)/config_${OS}_$(if $(USE_DEBUG),debug,release)_$(if $(USE_DEBUG_MEMORY),memckeck_)${LIB_AFF} $(DEP) $(OBJ_FILES)
	$(CMD_LINEFEED)
	@echo Creation de l executable $(if $(USE_DEBUG) ,en mode Debug)
	$(CXX) -o $(BIN_DIR)/$(EXEC_NAME) $(OBJ_FILES) $(LDFLAGS)


# Génère et inclut les dépendances
-include $(DEP)


# Génération des fichier .o ( dans le repertoire $(OBJ_DIR) )
$(OBJ_DIR)/%.o: %.cpp MakeFile.org
	$(CMD_LINEFEED)
	@echo Generation de $@ $(if $(USE_DEBUG) ,en mode Debug)
	$(CXX) $(CFLAGS) -o $@ -c $<


# Système de génération des dépendances
$(DEP): $(SRC) $(subst main.h,,$(SRC:.cpp=.h))
	$(CMD_CLEAR)
	@echo Generation des dependances
# Le sed est la pour permettre de mofidier les regles main.o:... --> obj/main.o:...
	$(CXX) $(CFLAGS) -MM $(SRC) | $(CMD_SED) -r "s/([^.]*)\.o:/$(OBJ_DIR)\/\1.o:/" > $(DEP)


# Auto création du dossier BIN_DIR
$(BIN_DIR):
	@echo Creation du dossier "$(BIN_DIR)"
	mkdir $(BIN_DIR)


# Auto création du dossier OBJ_DIR
$(OBJ_DIR):
	@echo Creation du dossier "$(OBJ_DIR)"
	mkdir $(OBJ_DIR)


################################################################################
# Règles utilisable par appel externe ( make XXX )
################################################################################

# Make depend ( régénération manuel des dep )
.PHONY: depend dep exec valgrind clean clean_dep pfiles help debug ncurses sdl sfml doxygen no_clear memcheck memchk
depend: $(DEP)
dep: $(DEP)


# Désactive la commande $(CMD_CLEAR)
no_clear:


# Lancer le prog
exec: $(BIN_DIR)/$(EXEC_NAME)
ifeq ($(OS), linux)
	cd $(BIN_DIR) && $(if $(and $(USE_DEBUG),$(DEBUG_AUTO_EXEC_GDB)) ,gdb $(EXEC_NAME) ,./$(EXEC_NAME))
else
	cd $(BIN_DIR) && $(if $(and $(USE_DEBUG),$(DEBUG_AUTO_EXEC_GDB)) ,gdb $(EXEC_NAME) ,$(EXEC_NAME))
endif
# On look si on a fait appel a memcheck => On affiche le résultat
ifneq ($(or $(findstring memcheck,$(MAKECMDGOALS)),$(findstring memchk,$(MAKECMDGOALS)),$(DEBUG_MEMORY)),)
	$(call ECHO ,Detail des allocations memoires ${ECHO_(}Fichier: bin/allocations.txt${ECHO_)})
	@cd bin && $(CMD_CAT) allocations.txt
endif


# Regle pour le mode debug
debug: $(BIN_DIR)/$(EXEC_NAME)


# Regle pour le mode ncurses
ncurses: $(BIN_DIR)/$(EXEC_NAME)


# Regle pour le mode sdl
sdl: $(BIN_DIR)/$(EXEC_NAME)


# Regle pour le mode sfml
sfml: $(BIN_DIR)/$(EXEC_NAME)


# Règle pour effectuer un MemCheck sur le prog
memchk: $(BIN_DIR)/$(EXEC_NAME)
memcheck: $(BIN_DIR)/$(EXEC_NAME)


# Cette règle permet de savoir si on était en mode debug ou pas
# Si on était en release et qu'on passe en debug -> clean all
# Si on était en debug et qu'on passe en release -> clean all
$(OBJ_DIR)/config_%:
	$(CMD_LINEFEED)
	@echo "Changement de type de compilation Debug <-> Release & Ncurses <-> SDL <-> SFML"
#	@$(MAKE) --silent --no-print-directory --makefile=MakeFile.org clean no_clear
#	Suppression des .o et du fichier de config, le .depend a toutes les config dé
	cd $(OBJ_DIR) && $(CMD_DEL) *.o config_*
	@echo .>$@


# Valgrind
valgrind: $(BIN_DIR)/$(EXEC_NAME)
	$(CMD_CLEAR)
	@echo Lancement de Valgrind
	@cd $(BIN_DIR) && valgrind --tool=memcheck --leak-check=full --track-origins=yes --log-file=valgrind.txt ./$(EXEC_NAME)
	@cd $(BIN_DIR) && $(CMD_CAT) valgrind.txt


# Doxygen
doxygen: $(DOXYGEN_DIR)/Doxyfile
	$(CMD_CLEAR)
	@echo Lancement de Doxygen
	cd $(DOXYGEN_DIR) && doxygen


# Pour créer une archive tar bz2
tar:
	$(call ECHO ,Creation de l'archive du projet)
	@$(CMD_DEL) bomberman.tar.bz2
	@tar -jcvf bomberman.tar.bz2 *.cpp *.h *.inl MakeFile.org makefile $(DOXYGEN_DIR)/Doxyfile TODO.txt _CodingStyle_.txt $(BIN_DIR)/map/*.map $(BIN_DIR)/Chicken\ Butt.ttf $(BIN_DIR)/images/*.png ClientServer/*.h ClientServer/*.cpp ClientServer/*.inl ClientServer/Client/*.h ClientServer/Client/*.cpp ClientServer/Server/*.h ClientServer/Server/*.cpp ClientServer/Server/*.inl


# Make clean
clean:
	$(CMD_CLEAR)
	@echo "Suppression des fichiers .o, (de l'executable et) du fichier des dependances"
	$(CMD_DEL) $(DEP)
# Pour supprimer les .o dans le dossier obj ( bizari de windows ... )
	cd $(OBJ_DIR) && $(CMD_DEL) *.o config_*


# Supprime aussi les executables obtenu
clean_all: clean
	cd $(BIN_DIR) && $(CMD_DEL) *.exe


# Make clean dep
clean_dep:
	$(CMD_CLEAR)
	@echo Suppression du fichier de dependances
	$(CMD_DEL) $(DEP)


# Affiche les fichiers utilisés
pfiles:
	$(CMD_CLEAR)
	$(call ECHO ,=================================== Bomberman ==================================)
	$(call ECHO ,Sources:)
	$(call ECHO ,	$(SRC))
	$(call ECHO ,Dependances:)
	@$(CXX) $(CFLAGS) -MM $(SRC) | $(CMD_SED) -e "s/^/	/"
	$(call ECHO ,Executable obtenu:)
	$(call ECHO ,	$(BIN_DIR)/$(EXEC_NAME))


# Affichage de l'aide
help:
	$(CMD_CLEAR)
	$(call ECHO ,Aide du MakeFile de Bomberman)
	$(CMD_LINEFEED)
	$(call ECHO ,make ARG [no_clear])
	$(call ECHO ,	all:		Construit tout le projet.)
	$(call ECHO ,	debug:		Construit tout le projet en debug (gdb).)
	$(call ECHO ,	ncurses:	Construit tout le projet avec la lib Ncurses.)
	$(call ECHO ,	sdl:		Construit tout le projet avec la lib SDL.)
	$(call ECHO ,	sfml:		Construit tout le projet avec la lib SFML.)
	$(call ECHO ,	clean:		Supprime les fichiers .o, et le fichier de)
	$(call ECHO ,			dependances.)
	$(call ECHO ,	clean_all:	Supprime les fichiers .o, l'executable et le fichier de)
	$(call ECHO ,			dependances.)
	$(call ECHO ,	clean_dep:	Supprime le fichier des dependances.)
	$(call ECHO ,	depend:		Construit le fichier des dependances - Le fichier est :)
	$(call ECHO ,			supprime a chaque fin de compilations et est donc auto)
	$(call ECHO ,			regenere a chaque compilation)
	$(call ECHO , 	dep:		IDEM {make depend}.)
	$(call ECHO ,	valgrind:	Compil le projet puis lance valgrind sur le projet.)
	$(call ECHO ,	tar:		Archive les fichiers dans un fichier tar.bz2)
	$(call ECHO ,	doxygen:	Execute doxygen sur le projet.)
	$(call ECHO ,	no_clear:	Annule tous les effacements d'ecran)
	$(call ECHO ,	exec:		{make all} et execute l'executable obtenu.)
	$(call ECHO ,	memcheck:	{make all} avec ajout du systeme de debug memoire, )
	$(call ECHO ,			execute l'executable obtenu et retourne les resultats)
	$(call ECHO ,			memoire.)
	$(call ECHO ,	memchk:		Alias de memcheck)
	$(call ECHO ,	exec:		{make all} et execute l'executable obtenu.)
	$(call ECHO ,	pfiles:		Affiche les fichiers utilises)
	$(call ECHO ,	help:		Affiche cette aide.)
	$(CMD_LINEFEED)
	$(call ECHO ,/!\ Si MAKE n'a pas d'ARG alors IDEM a {make all} avec la lib $(LIB_AFF).)
	$(call ECHO ,/!\ L'outil sed est utilise par ce makefile pour la generation des dependances !)
